### ISSUE TITLE
From 16x16 to 48x48 some png icons have no symbols

### ISSUE THREAD

**Issue by rafaelmardojai** [snwh/suru-icon-theme#2]
Like `calendar-app.png` or `filemanager-app.png`.

**Comment by snwh** [comment]
From the README:
 > Please note: this icon theme is in development, it will not be a perfect experience on your desktop

**Comment by snwh** [comment]
So yes, some icons are incomplete

**Comment by rafaelmardojai** [comment]
Oh, sorry, i'm just testing. I didn't noticed that source files have different design by size. Too much appreciated the scaling work.

Very grateful that you have started this project.
Regards.

**Comment by snwh** [comment]
No worries. Designing for the specific sizes gives a theme a more polished feel overall (something I do in all my themes that many others do not).

**Comment by mymike00** [comment]
why not just scaling the icons for smaller sizes? it would be better than an empty icon with only the background. I suggest this for now that the theme is under development, but it would give a better user experience, imho...

**Comment by snwh** [comment]
@mymike00 because relying on scaling is a lazy way to design icons and gives imperfect results. I only worry about the user experience when the theme is "officially released" –it's in-development and I've give ample warning/notice about how incomplete it is. If it's being packaged or distributed to users in this state then `¯\_(ツ)_/¯ `

**Comment by mymike00** [comment]
OK, I perfectly understand you. Thanks very much for the work you had done since now!!!
I hope you'll finish soon this fantastic icon set
