### ISSUE TITLE
ppa and packaging stuff

### ISSUE THREAD

**Issue by merlijn-sebrechts** [snwh/suru-icon-theme#20]
I created a mirror of the `suru-icon-theme` repo in the `ubuntu` github project:  <https://github.com/Ubuntu/suru-icon-theme>. I'm setting something up to pull from your repo daily. I added packaging stuff and included it in the daily builds for the communitheme ppa. You can install it on Ubuntu 17.10 and 18.04 using the ppa:

```bash
sudo add-apt-repository ppa:communitheme/ppa
sudo apt update
sudo apt install suru-icon-theme
```
and change the icon theme using "Gnome Tweaks".

If you're interested, I can create a PR to upstream the packaging stuff, and add a link to the ppa in your readme. What do you think?

*[I posted this on the ubuntu community forum first, but I'm not sure if you watch that.](https://community.ubuntu.com/t/icon-theme-discussions/1925/3)*

**Comment by snwh** [comment]
I'm not going to endorse any packaged versions of the theme at this point in Suru's development. It is in a pre-release state and shouldn't be being distributed or packaged in my view (aside from downloading and installing from source). I'd like to avoid getting flooded with issues outside of the focus of development, which usually happens when a lot folks get their hands on something.

Also, I see no need to include the packaging stuff in this repo. In my other themes, I've always excluded the packaging stuff and kept it separate, to avoid cluttering the main repository. For example, with my Paper icon set, I keep [a branch on Launchpad](http://bazaar.launchpad.net/~snwh/paper-icon-theme/deb-packaging/files) with all the debian stuff that is the basis for a [PPA build recipe](https://code.launchpad.net/~snwh/+recipe/paper-icon-theme-daily).

*Yeah, I'm not watching the community forum (or any forum). Emailing me is the best course of action, or filing issues if it's directly about the icons. Forums are not useful or constructive in my view as there's often a lot of noise, see: the entire thread about the new themes.*

**Comment by merlijn-sebrechts** [comment]
Fair enough. The reason I packaged it is because we want an easy way for the theme designers to see how everything fits together, and what actually works in Ubuntu. I'll make sure to include a big warning about the pre-release state of everything.

**Comment by snwh** [comment]
@galgalesh the build system should be sufficiently easy enough for other developers 😉 It's just as soon as a PPA exists it gets picked up by the blogs and then it's a whole thing.

**Comment by merlijn-sebrechts** [comment]
I removed my comment about the PPA from the forum and updated the description of the PPA in launchpad to explicitly state not to make this public. The PPA is also not available for the lts, which greatly reduces the number of people who can install it.

But don't underestimate how hard this stuff is if you're new to this. Even with the PPA, some of the designers are still having issues ;).

*Sidenote; You might also want to look at creating a github issue template where you explain what kind of issues you'd like to get at this point.*

**Comment by jebeld17** [comment]
Is the PPA still in development?
