### ISSUE TITLE
Inherit from ubuntu-mono-dark?

### ISSUE THREAD

**Issue by merlijn-sebrechts** [snwh/suru-icon-theme#37]
Hi

I've gotten a request to make Suru icon theme inherit from `ubuntu-mono-dark` and I wanted to know your take on it. *I see you've added `ubuntu-mono-light` in the past to fix issues like https://github.com/snwh/suru-icon-theme/issues/21. You removed it again quickly after, but I can't seem to find why.*

`ubuntu-mono-dark` contains a number of mono "systray" icons for apps like Dropbox and transmission. Example for Dropbox:

**ubuntu-mono-dark (default in Ubuntu)**

![image](https://user-images.githubusercontent.com/1492981/38390386-710b265a-3921-11e8-8349-f83aee461fc9.png)

**default of dropbox**

![image](https://user-images.githubusercontent.com/1492981/38390424-9216fe00-3921-11e8-93d3-6b22a9e2fe5e.png)

I don't like the fact that `ubuntu-mono-dark` overrides the dropbox icon, but it's currently the default in Ubuntu, and it does fix the issue with the transmission icon.

What do you think?

**Comment by snwh** [comment]
The mono themes were a very hacky (problematic) way of doing two colours since Unity didn't support the `*-symbolic` icon variant, so inheriting them runs into other problems with app icons (hence my quick reversal).

The mono themes were also designed for Unity which had a system tray but that's a deprecated aspect of GNOME. I want this theme forward thinking not backward. Supporting legacy features = more work and I already don't have that much time to work on Suru. 

Eventually the Humanity inheritance will be dropped and some of these issues will be gone.

**Comment by merlijn-sebrechts** [comment]
Ok, makes sense.

**Comment by febcrash** [comment]
Same issue with Tomboy and Diodon applets
