### ISSUE TITLE
New symbols for window controls

### ISSUE THREAD

**Issue by ghost** [snwh/suru-icon-theme#40]
The symbols for window controls look very conservative. Probably because they are part of the fallback-icon-theme.
Suru should get its own window controls.
It would be nice when the minimize-symbol implicates that the window is going to be minimized to the left border of the screen (dock).
Thank you!

**Comment by wandrewkeech** [comment]
I really like the very Suru style of the current icons.

**Comment by ghost** [comment]
hmmm... i mean this:
![bildschirmfoto von 2018-04-14 13-48-16](https://user-images.githubusercontent.com/36449926/38768065-3127b110-3fee-11e8-9b26-dc54471864f8.png)
Couldn't they be a tiny bit bigger and have a little touch of roundness?

**Comment by snwh** [comment]
I hear this a lot about established icons (not just window controls). The existing symbols used for the icons of window controls are widely used and recognised quickly, introducing new symbols needlessly introduces confusion. What you're calling conservatism is actually consistency–familiarity and being consistent with established window control icons is good for (new and existing) users.

**Comment by ghost** [comment]
Hallo @snwh 
Thank you for your answer. You are right, they are widely used. Mainly on windows-computers. Apple uses a different style.
But wouldn't it be a good opportunity to show something completely original? Not a question to answer. Just think about it. Pretty sure you would make something really good.
And by "new users" we should think about real "new users". Children, old people or people in development countries who are using a computer for the first time. Windows-users know what the symbols mean, no matter which are used.

**Comment by snwh** [comment]
Originality is something I leave to artists. 😉I’m more concerned with universality, introducing “original” concepts narrows or eliminates the accessibility to whatever is being designed and makes something less approachable –this applies to things as minor as a window control icon in my mind. The current icons are the most universal for those actions and are consistent with similar actions across desktops that have similar windowing systems. 

I’m of the philosophy “if it ain’t broke don’t fix it” and what you propose seems like change for change’s sake.

**Comment by ghost** [comment]
With that philosophy it wouldn't even be necessary to change the icon-theme in the first place. Or the default-theme. We would all continue using ambiance or adwaita.

But i have done my part. I asked, proposed and shared possible ideas or inspiration and you answered. Thank you.

**Comment by lukeblevins** [comment]
I would like to introduce a concept of new titlebar buttons. These will be animated.
I was thinking we should have three stationary images of a square for the close, maximize, and minimize title bar icons. The square should represent the window frame. Next, when a user hovers over the icon, it should play a quick animation that hints to what it does.

For example:
Minimize pushes the square out of view (into the outside of the titlebar).
Maximize pushes the square up into view (from outside the titlebar). Or possibly a shrunk/enlarged square to represent resizing.
Close will display an X over its respective square and fade out the entire square and X.

Please note: No shapes or icons will be drawn outside the titlebar, as it is only theoretical because it is part of the animation.

Take a look below -
![1024bcc61593f6bc563554210a51e327936c4da2](https://user-images.githubusercontent.com/20365014/38934203-2919fbba-42e9-11e8-9c3b-1768ee037b99.jpg)

UPADATE: Minimize Concept added
![f6d825084ee221f13dba1dd9188822df1faef721](https://user-images.githubusercontent.com/20365014/38934229-3f701854-42e9-11e8-8141-14ec0f06296d.gif)

I thought this would be an interesting concept to let the community decide on. It would add some playful personality to the UI, while maintaining ease of access and minimalism when not needed. I will look into animating my concept to bring it to life. Hopefully, no technical limitations stand in the way.

**Comment by snwh** [comment]
@duke7553 actually that concept will result in poorer usability since all meaning would  been hidden behind the animations and no one could tell what’s what just by looking at it—it’s gone from one interaction (looking at the icon to get the meaning) to three (looking, moving cursor to confirm, watching animation). Not to mention animating commonly used actions would be introducing delay and distractions.

At nearly all times icons should be static elements.

**Comment by lukeblevins** [comment]
@snwh Yeah, I can see how that would be an issue. I guess our current implementation is perfectly sufficient. Boy, I had fun making the concept rendering, though. Keep up the great work
