### ISSUE TITLE
Unread notification icon can be misleading

### ISSUE THREAD

**Issue by ghost** [snwh/suru-icon-theme#44]
![notificationdot](https://user-images.githubusercontent.com/36449926/39395948-d7ff54b4-4ae5-11e8-95f8-2650513c39a3.png)
The unread notification icon looks like a sun and can be misinterpreted as a weather-notification. Other icon-themes use a more obvious icon to avoid misinterpretation:
![39395264-dffa3782-4adc-11e8-8317-382760829932](https://user-images.githubusercontent.com/36449926/39395977-3b123dd2-4ae6-11e8-965c-5a539cb8b6f4.png)

We discussed this on the communitheme-gnome-shell-rep and would welcome a new icon:
https://github.com/ubuntu/gnome-shell-communitheme/issues/144

**Comment by snwh** [comment]
It's not an icon. It's a text entity that's part of GNOME shell, I have no control over what that is in the icon theme unless they changed it recently to be an icon.

**Comment by snwh** [comment]
Also, I was involved in the GNOME design discussions around the notification indicator and a bell was explored as a concept but the dot was landed on as the best solution–I'm not about to override design decisions just for the sake of it.

**Comment by snwh** [comment]
The proposed icon is actually more "misleading". To have a bell icon for the changed "new notification" state, like the example, would require the default "no notifications" state icon to be always present on the top panel which it isn't–a bell is used in the elementary icon set since the notification menu is always present in the panel as an "unrung" bell:

![screenshot from 2018-04-28 10-10-57](https://user-images.githubusercontent.com/1217306/39397391-796ffcf0-4acc-11e8-9f41-dcedff912fc9.png)
