### ISSUE TITLE
Third-party app developer here...

### ISSUE THREAD

**Issue by ztefn** [snwh/suru-icon-theme#45]
Hello Sam,

I'm the developer of an app named [Haguichi](https://github.com/ztefn/haguichi) and would like to make clear that I am totally fine with icon themes "overwriting" my "branding" as long as it incorporates the logo and color. I would even go as far to say that I _prefer_ this, because it provides desktop integration and consistency, which I strongly advocate.

I prefer this so much so, that I often [create](https://github.com/KDE/breeze-icons/commit/438730736c7e47333cce78bb6d897c3d5fc0c808) [these](https://github.com/mate-desktop/mate-icon-theme-faenza/pull/15) [icons](https://github.com/linuxmint/mint-x-icons/pull/137) myself and submit them upstream to the icon theme. If pushing upstream is not possible and it's a major (default) distribution theme, I will ship the icons with my app itself. That's what I have done with ubuntu-mono icons and it's what I'm about to do with Suru icons in the upcoming 1.4.0 release:

![Haguichi Suru Icon](https://raw.githubusercontent.com/ztefn/haguichi/master/data/icons/Suru/256x256/apps/haguichi.png)

https://github.com/ztefn/haguichi/tree/master/data/icons

So, is this really how you want this to be done? Or do you want me to create a pull request to include them in the proper package; Suru itself.

**Comment by snwh** [comment]
Hello, I do know that there are probably many folks like you who are fine with it but I maintain that it's it's still the app developer's choice to make and not mine, especially for a system icon set and not a third-party icon theme.

Your approach is what I think is the ideal. If an application developer wants to ship icons for tighter style integration, they can. Otherwise it becomes and endless task for me or any other icon set designer–I am still flooded with requests for icon additions for my third themes–which is why I've drawn a strict line with Suru.

I am all to happy to work with app developers to create icons for their apps to aid in integration and consistency and I'll take a look at yours.

**Comment by ztefn** [comment]
Haguichi 1.4.0 [has now been released](https://www.haguichi.net/news/release140/), including the Suru theme app icons. Thanks again @snwh for making it fit perfectly!
