### ISSUE TITLE
Request: change size threshold of folder icons 

### ISSUE THREAD

**Issue by Feichtmeier** [snwh/suru-icon-theme#56]
![yurps](https://user-images.githubusercontent.com/15329494/41223858-3f0d9ed4-6d6b-11e8-95db-a38e842a7841.gif)

At the default icon size (I believe that's 67%) of the NautilusCanvasViewContainter (just a view basically) suru uses the "smaller" icons for the folders.

Could this be changed so the very beautiful and flatter icons are used for this size?

Best wishes

**Comment by mymike00** [comment]
yeah, I'd like that too
or just change the smaller folder icon so they looks more like the bigger one

**Comment by snwh** [comment]
Well, I have no control over the icon thresholds.

I mean, there is a reason the 48x48 and smaller icons are in that style because shapes and edges begin to lose their distinction as the icon gets smaller and in order to keep the icon well-defined and legible the design makes use of highlights and strokes. Just having the two colored shapes that compose the icon is usually not sufficient contrast at smaller sizes.

I'll play around with it though and see what I can come up with.

**Comment by snwh** [comment]
If were to change the 48x48 pixel icon for folders, I would have to change all 48x48 icons to be consistent across the icon set...

**Comment by mymike00** [comment]
Yeah, but personally I don't like the black stroke around the icons...

**Comment by snwh** [comment]
@mymike00 it's a relic of legacy interfaces when displays were low resolution and icons needed to be legible. You may not like it, it's a common icon design principle that's pretty necessary :wink: especially for small icon sizes, unless you go completely pictographic like the symbolic icon set that's common in modern UIs.

**Comment by mymike00** [comment]
> If were to change the 48x48 pixel icon for folders, I would have to change all 48x48 icons to be consistent across the icon 

if you give me a template/example I can help you copying it to the whole theme
