### ISSUE TITLE
Missing Icon: extension

### ISSUE THREAD

**Issue by Feichtmeier** [snwh/suru-icon-theme#70]
![image](https://user-images.githubusercontent.com/15329494/41927335-3a7a6196-7972-11e8-9ff3-91ed7e9bb873.png)

The little puzzle icon that can be found for example in gnome-todo.
In the highcolor icon set it is named "eog-plugin" (eye of gnome) :man_shrugging: 
![image](https://user-images.githubusercontent.com/15329494/41927460-95b17914-7972-11e8-999e-d4781851cf0b.png)

**Comment by snwh** [comment]
The GTK inspector tells me (in To-do at least) it's `libpeas-plugin`. 

![screenshot from 2018-06-27 09-20-31](https://user-images.githubusercontent.com/1217306/41976537-60c15d22-79eb-11e8-8bea-ef223bd74828.png)

It's clearly providing it's own icon and using a non-standard one and I'm not gonna start providing an icon for every app-specific icon. That would start me down an endless task, since many many apps just dump random icons in `hicolor` and call it a day. See: whatever those other two are in your screenshot.

Imperfect coverage is going to be a thing with this icon set that folks will have to live with.

**Comment by snwh** [comment]
Closing since the actual addon/extension icon is [already present](https://github.com/snwh/suru-icon-theme/blob/master/Suru/256x256/mimetypes/application-x-addon.png). Perhaps a bug should be files against this app for not referencing a standard icon.

**Comment by Feichtmeier** [comment]
Oh yeah indeed! Thanks for the clarification!
